# Generated by Django 6.0.4 on 2026-04-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableResto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('table_status', models.CharField(choices=[('Kosong', 'Kosong'), ('Terisi', 'Terisi')], default='Kosong', max_length=15)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
                ('user_created', models.CharField(blank=True, max_length=100, null=True)),
                ('user_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
